
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package jflex.examples.minijava;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQEQ = 9;
  public static final int ABSTRACT = 2;
  public static final int BOOLEAN = 3;
  public static final int STRING_LITERAL = 7;
  public static final int PLUS = 10;
  public static final int EQ = 8;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int IDENTIFIER = 5;
  public static final int BREAK = 4;
  public static final int INTEGER_LITERAL = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ABSTRACT",
  "BOOLEAN",
  "BREAK",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "STRING_LITERAL",
  "EQ",
  "EQEQ",
  "PLUS"
  };
}

