// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/proyectoCompilador/scannerCup.jflex

package proyectoCompilador;
import java_cup.runtime.Symbol;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class ScannerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  3,  2,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  4,  5,  0,  0,  6,  7,  8,  9, 10, 11, 12, 13, 12, 14, 15, 
    16, 17, 18, 19, 20, 21, 22, 16, 23, 16, 24, 25, 26, 27, 28, 29, 
     0, 30, 30, 30, 30, 30, 31, 32, 32, 32, 32, 32, 32, 32, 33, 32, 
    34, 32, 32, 32, 35, 32, 32, 32, 32, 32, 32, 36, 37, 38, 39,  0, 
     0, 40, 41, 42, 43, 44, 45, 46, 47, 48, 32, 49, 50, 51, 52, 53, 
    54, 32, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,  0, 
     0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\1"+
    "\1\6\1\7\2\4\1\10\1\11\1\4\1\12\1\13"+
    "\1\14\1\3\1\15\1\3\1\16\4\17\1\20\1\21"+
    "\1\22\21\17\1\23\1\5\1\24\1\5\1\3\1\0"+
    "\1\25\3\0\1\12\1\0\1\2\1\12\1\0\3\17"+
    "\1\0\1\17\1\26\10\17\1\27\11\17\1\30\26\17"+
    "\6\0\3\17\1\0\15\17\1\31\2\17\1\26\2\17"+
    "\1\32\22\17\1\33\1\17\2\0\1\17\1\34\1\0"+
    "\2\17\1\32\1\17\1\32\1\35\3\17\1\36\1\37"+
    "\3\17\2\0\2\17\1\32\13\17\1\35\4\17\1\40"+
    "\2\17\1\32\2\17\1\0\2\17\1\41\10\17\2\0"+
    "\21\17\1\42\1\43\1\44\10\17\1\45\5\17\1\46"+
    "\1\47\1\17\1\50\7\17\1\51\1\52\1\53\3\17"+
    "\1\54\1\55\1\17\1\56\1\57\4\17";

  private static int [] zzUnpackAction() {
    int [] result = new int[278];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\104\0\104\0\210\0\314\0\104\0\u0110\0\u0154"+
    "\0\104\0\104\0\u0198\0\u01dc\0\104\0\u0220\0\u0264\0\u02a8"+
    "\0\104\0\104\0\u02ec\0\210\0\u0330\0\104\0\u0374\0\u03b8"+
    "\0\u03fc\0\u0440\0\104\0\104\0\u0484\0\u04c8\0\u050c\0\u0550"+
    "\0\u0594\0\u05d8\0\u061c\0\u0660\0\u06a4\0\u06e8\0\u072c\0\u0770"+
    "\0\u07b4\0\u07f8\0\u083c\0\u0880\0\u08c4\0\u0908\0\104\0\u094c"+
    "\0\104\0\104\0\104\0\314\0\104\0\u0990\0\u0154\0\u09d4"+
    "\0\u0220\0\u0a18\0\u0a5c\0\u0aa0\0\u0ae4\0\u0b28\0\u0b6c\0\u0bb0"+
    "\0\u0bf4\0\u0c38\0\u0374\0\u0c7c\0\u0cc0\0\u0d04\0\u0d48\0\u0d8c"+
    "\0\u0dd0\0\u0e14\0\u0e58\0\u0374\0\u0e9c\0\u0ee0\0\u0f24\0\u0f68"+
    "\0\u0fac\0\u0ff0\0\u1034\0\u1078\0\u10bc\0\u0374\0\u1100\0\u1144"+
    "\0\u1188\0\u11cc\0\u1210\0\u1254\0\u1298\0\u12dc\0\u1320\0\u1364"+
    "\0\u13a8\0\u13ec\0\u1430\0\u1474\0\u14b8\0\u14fc\0\u1540\0\u1584"+
    "\0\u15c8\0\u160c\0\u1650\0\u1694\0\u16d8\0\u171c\0\u1760\0\u17a4"+
    "\0\u17e8\0\u0220\0\u182c\0\u1870\0\u18b4\0\u18f8\0\u193c\0\u1980"+
    "\0\u19c4\0\u1a08\0\u1a4c\0\u1a90\0\u1ad4\0\u1b18\0\u1b5c\0\u1ba0"+
    "\0\u1be4\0\u1c28\0\u1c6c\0\u0374\0\u1cb0\0\u1cf4\0\u1d38\0\u1d7c"+
    "\0\u1dc0\0\u1e04\0\u1e48\0\u1e8c\0\u1ed0\0\u1f14\0\u1f58\0\u1f9c"+
    "\0\u1fe0\0\u2024\0\u2068\0\u20ac\0\u20f0\0\u2134\0\u2178\0\u21bc"+
    "\0\u2200\0\u2244\0\u2288\0\u22cc\0\u0374\0\u2310\0\u2354\0\u2398"+
    "\0\u23dc\0\u0374\0\u2420\0\u2464\0\u24a8\0\u0374\0\u24ec\0\u2530"+
    "\0\u2574\0\u25b8\0\u25fc\0\u2640\0\u0374\0\u0374\0\u2684\0\u26c8"+
    "\0\u270c\0\u2750\0\u2794\0\u27d8\0\u281c\0\u2860\0\u28a4\0\u28e8"+
    "\0\u292c\0\u2970\0\u29b4\0\u29f8\0\u2a3c\0\u2a80\0\u2ac4\0\u2b08"+
    "\0\u2b4c\0\u0374\0\u2b90\0\u2bd4\0\u2c18\0\u2c5c\0\u0374\0\u2ca0"+
    "\0\u2ce4\0\u2d28\0\u2d6c\0\u2db0\0\u2df4\0\u2e38\0\u2e7c\0\u0374"+
    "\0\u2ec0\0\u2f04\0\u2f48\0\u2f8c\0\u2fd0\0\u3014\0\u3058\0\u309c"+
    "\0\u30e0\0\u3124\0\u3168\0\u31ac\0\u31f0\0\u3234\0\u3278\0\u32bc"+
    "\0\u3300\0\u3344\0\u3388\0\u33cc\0\u3410\0\u3454\0\u3498\0\u34dc"+
    "\0\u3520\0\u3564\0\u35a8\0\u0374\0\u0374\0\104\0\u35ec\0\u3630"+
    "\0\u3674\0\u36b8\0\u36fc\0\u3740\0\u3784\0\u37c8\0\104\0\u380c"+
    "\0\u3850\0\u3894\0\u38d8\0\u391c\0\u0374\0\u3960\0\u39a4\0\u0374"+
    "\0\u39e8\0\u3a2c\0\u3a70\0\u3ab4\0\u3af8\0\u3b3c\0\u3b80\0\u0374"+
    "\0\u0374\0\u0374\0\u3bc4\0\u3c08\0\u3c4c\0\u0374\0\u0374\0\u3c90"+
    "\0\u0374\0\u0374\0\u3cd4\0\u3d18\0\u3d5c\0\u3da0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[278];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\10\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\2\27\1\31\1\32\1\33\1\2\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\27\1\44\1\45"+
    "\2\27\1\46\2\27\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\27\1\56\1\27\1\57\1\60\1\61"+
    "\1\62\137\0\1\63\50\0\2\64\1\0\2\64\1\65"+
    "\37\64\1\66\36\64\7\0\1\63\74\0\2\67\1\0"+
    "\5\67\1\65\34\67\1\70\36\67\13\0\1\62\17\0"+
    "\1\6\103\0\1\6\70\0\10\71\67\0\1\72\3\0"+
    "\1\73\13\0\1\6\66\0\1\74\1\0\10\20\24\0"+
    "\1\75\61\0\1\62\1\63\103\0\1\63\1\62\67\0"+
    "\10\27\6\0\6\27\4\0\30\27\24\0\10\27\6\0"+
    "\6\27\4\0\1\76\27\27\24\0\10\27\6\0\6\27"+
    "\4\0\17\27\1\77\10\27\24\0\10\27\6\0\6\27"+
    "\4\0\17\27\1\100\10\27\24\0\10\101\74\0\10\27"+
    "\6\0\6\27\4\0\3\27\1\102\14\27\1\103\7\27"+
    "\24\0\10\27\6\0\6\27\4\0\1\104\14\27\1\105"+
    "\1\27\1\106\6\27\1\107\1\27\24\0\10\27\6\0"+
    "\6\27\4\0\1\110\14\27\1\111\12\27\24\0\10\27"+
    "\6\0\6\27\4\0\1\112\3\27\1\113\10\27\1\114"+
    "\12\27\24\0\10\27\6\0\6\27\4\0\12\27\1\115"+
    "\1\27\1\116\4\27\1\117\6\27\24\0\10\27\6\0"+
    "\6\27\4\0\10\27\1\120\4\27\1\121\1\27\1\122"+
    "\2\27\1\123\5\27\24\0\10\27\6\0\6\27\4\0"+
    "\4\27\1\124\10\27\1\125\12\27\24\0\10\27\6\0"+
    "\6\27\4\0\5\27\1\126\5\27\1\127\1\130\13\27"+
    "\24\0\10\27\6\0\6\27\4\0\1\131\7\27\1\132"+
    "\4\27\1\133\12\27\24\0\10\27\6\0\6\27\4\0"+
    "\1\134\16\27\1\135\2\27\1\136\5\27\24\0\10\27"+
    "\6\0\6\27\4\0\4\27\1\137\23\27\24\0\10\27"+
    "\6\0\6\27\4\0\4\27\1\140\10\27\1\141\3\27"+
    "\1\142\5\27\1\143\24\0\10\27\6\0\6\27\4\0"+
    "\7\27\1\144\7\27\1\145\10\27\24\0\10\27\6\0"+
    "\6\27\4\0\5\27\1\146\2\27\1\147\17\27\24\0"+
    "\10\27\6\0\6\27\4\0\1\150\7\27\1\151\17\27"+
    "\24\0\10\27\6\0\6\27\4\0\4\27\1\152\2\27"+
    "\1\153\20\27\24\0\10\27\6\0\6\27\4\0\4\27"+
    "\1\154\23\27\105\0\1\63\66\0\1\64\5\0\1\155"+
    "\2\0\1\156\72\0\1\67\5\0\1\157\2\0\1\160"+
    "\6\0\13\72\1\161\70\72\2\73\2\0\100\73\20\0"+
    "\10\74\24\0\1\75\43\0\1\162\3\0\10\71\74\0"+
    "\10\27\6\0\6\27\4\0\12\27\1\163\15\27\24\0"+
    "\10\27\6\0\6\27\4\0\1\164\27\27\24\0\10\27"+
    "\6\0\6\27\4\0\22\27\1\165\5\27\22\0\1\166"+
    "\105\0\10\27\6\0\6\27\4\0\3\27\1\167\24\27"+
    "\24\0\10\27\6\0\6\27\4\0\12\27\1\170\15\27"+
    "\24\0\10\27\6\0\6\27\4\0\15\27\1\171\12\27"+
    "\24\0\10\27\6\0\6\27\4\0\4\27\1\172\23\27"+
    "\24\0\10\27\6\0\6\27\4\0\21\27\1\173\6\27"+
    "\24\0\10\27\6\0\6\27\4\0\12\27\1\174\15\27"+
    "\24\0\10\27\6\0\6\27\4\0\14\27\1\175\13\27"+
    "\24\0\10\27\6\0\6\27\4\0\26\27\1\176\1\27"+
    "\24\0\10\27\6\0\6\27\4\0\12\27\1\177\15\27"+
    "\24\0\10\27\6\0\6\27\4\0\20\27\1\200\7\27"+
    "\24\0\10\27\6\0\6\27\4\0\22\27\1\201\5\27"+
    "\24\0\10\27\6\0\6\27\4\0\7\27\1\202\20\27"+
    "\24\0\10\27\6\0\6\27\4\0\14\27\1\203\13\27"+
    "\24\0\10\27\6\0\6\27\4\0\17\27\1\204\10\27"+
    "\24\0\10\27\6\0\6\27\4\0\15\27\1\205\12\27"+
    "\24\0\10\27\6\0\6\27\4\0\14\27\1\206\13\27"+
    "\24\0\10\27\6\0\6\27\4\0\25\27\1\207\2\27"+
    "\24\0\10\27\6\0\6\27\4\0\22\27\1\210\5\27"+
    "\24\0\10\27\6\0\6\27\4\0\16\27\1\211\11\27"+
    "\24\0\10\27\6\0\6\27\4\0\21\27\1\212\6\27"+
    "\24\0\10\27\6\0\6\27\4\0\16\27\1\213\11\27"+
    "\24\0\10\27\6\0\6\27\4\0\14\27\1\214\13\27"+
    "\24\0\10\27\6\0\6\27\4\0\3\27\1\215\24\27"+
    "\24\0\10\27\6\0\6\27\4\0\26\27\1\216\1\27"+
    "\24\0\10\27\6\0\6\27\4\0\1\164\7\27\1\217"+
    "\17\27\24\0\10\27\6\0\6\27\4\0\1\27\1\220"+
    "\26\27\24\0\10\27\6\0\6\27\4\0\21\27\1\221"+
    "\6\27\24\0\10\27\6\0\6\27\4\0\2\27\1\222"+
    "\11\27\1\223\13\27\24\0\10\27\6\0\6\27\4\0"+
    "\12\27\1\224\15\27\24\0\10\27\6\0\6\27\4\0"+
    "\17\27\1\225\10\27\24\0\10\27\6\0\6\27\4\0"+
    "\1\226\27\27\24\0\10\27\6\0\6\27\4\0\10\27"+
    "\1\227\17\27\24\0\10\27\6\0\6\27\4\0\1\230"+
    "\27\27\24\0\10\27\6\0\6\27\4\0\10\27\1\231"+
    "\17\27\24\0\10\27\6\0\6\27\4\0\14\27\1\232"+
    "\13\27\24\0\10\27\6\0\6\27\4\0\17\27\1\103"+
    "\10\27\24\0\10\27\6\0\6\27\4\0\4\27\1\233"+
    "\23\27\24\0\10\27\6\0\6\27\4\0\4\27\1\234"+
    "\3\27\1\235\17\27\24\0\10\27\6\0\6\27\4\0"+
    "\10\27\1\236\17\27\24\0\10\27\6\0\6\27\4\0"+
    "\1\210\27\27\45\0\1\156\103\0\1\237\103\0\1\160"+
    "\103\0\1\240\42\0\13\72\1\161\3\72\1\3\64\72"+
    "\20\0\10\27\6\0\6\27\4\0\20\27\1\165\7\27"+
    "\24\0\10\27\6\0\6\27\4\0\6\27\1\241\21\27"+
    "\24\0\10\27\6\0\6\27\4\0\4\27\1\242\23\27"+
    "\24\0\10\243\74\0\10\27\6\0\6\27\4\0\17\27"+
    "\1\244\10\27\24\0\10\27\6\0\6\27\4\0\1\245"+
    "\27\27\24\0\10\27\6\0\6\27\4\0\12\27\1\246"+
    "\15\27\24\0\10\27\6\0\6\27\4\0\1\247\27\27"+
    "\24\0\10\27\6\0\6\27\4\0\4\27\1\250\23\27"+
    "\24\0\10\27\6\0\6\27\4\0\12\27\1\251\15\27"+
    "\24\0\10\27\6\0\6\27\4\0\20\27\1\252\1\253"+
    "\6\27\24\0\10\27\6\0\6\27\4\0\20\27\1\235"+
    "\7\27\24\0\10\27\6\0\6\27\4\0\4\27\1\254"+
    "\23\27\24\0\10\27\6\0\6\27\4\0\4\27\1\255"+
    "\23\27\24\0\10\27\6\0\6\27\4\0\13\27\1\256"+
    "\14\27\24\0\10\27\6\0\6\27\4\0\4\27\1\257"+
    "\23\27\24\0\10\27\6\0\6\27\4\0\14\27\1\260"+
    "\13\27\24\0\10\27\6\0\6\27\4\0\13\27\1\103"+
    "\14\27\24\0\10\27\6\0\6\27\4\0\2\27\1\261"+
    "\25\27\11\0\1\262\2\0\1\263\7\0\10\27\6\0"+
    "\6\27\4\0\30\27\24\0\10\27\6\0\6\27\4\0"+
    "\17\27\1\176\10\27\24\0\10\27\6\0\6\27\4\0"+
    "\15\27\1\264\12\27\24\0\1\27\1\265\1\266\1\267"+
    "\1\246\1\27\1\270\1\246\6\0\6\27\4\0\4\27"+
    "\1\271\23\27\24\0\10\27\6\0\6\27\4\0\16\27"+
    "\1\272\11\27\24\0\10\27\6\0\6\27\4\0\22\27"+
    "\1\273\5\27\24\0\10\27\6\0\6\27\4\0\10\27"+
    "\1\274\17\27\24\0\10\27\6\0\6\27\4\0\1\275"+
    "\27\27\24\0\10\27\6\0\6\27\4\0\23\27\1\276"+
    "\4\27\24\0\10\27\6\0\6\27\4\0\12\27\1\277"+
    "\15\27\24\0\10\27\6\0\6\27\4\0\22\27\1\300"+
    "\5\27\24\0\10\27\6\0\6\27\4\0\15\27\1\301"+
    "\12\27\24\0\10\27\6\0\6\27\4\0\3\27\1\302"+
    "\24\27\24\0\10\27\6\0\6\27\4\0\10\27\1\303"+
    "\17\27\24\0\10\27\6\0\6\27\4\0\10\27\1\304"+
    "\11\27\1\305\5\27\24\0\10\27\6\0\6\27\4\0"+
    "\1\27\1\306\26\27\24\0\10\27\6\0\6\27\4\0"+
    "\20\27\1\307\7\27\24\0\10\27\6\0\6\27\4\0"+
    "\14\27\1\310\13\27\24\0\10\27\6\0\6\27\4\0"+
    "\25\27\1\311\2\27\24\0\10\27\6\0\6\27\4\0"+
    "\21\27\1\312\6\27\24\0\10\27\6\0\6\27\4\0"+
    "\24\27\1\103\3\27\24\0\10\27\6\0\6\27\4\0"+
    "\11\27\1\176\16\27\24\0\10\27\6\0\6\27\4\0"+
    "\12\27\1\313\15\27\45\0\1\64\103\0\1\67\62\0"+
    "\10\27\6\0\6\27\4\0\13\27\1\314\14\27\22\0"+
    "\1\315\105\0\10\27\6\0\6\27\4\0\4\27\1\316"+
    "\23\27\24\0\10\27\6\0\6\27\4\0\14\27\1\317"+
    "\13\27\24\0\10\27\6\0\6\27\4\0\11\27\1\320"+
    "\16\27\24\0\10\27\6\0\6\27\4\0\20\27\1\312"+
    "\7\27\24\0\10\27\6\0\6\27\4\0\2\27\1\321"+
    "\25\27\24\0\10\27\6\0\6\27\4\0\21\27\1\322"+
    "\6\27\24\0\10\27\6\0\6\27\4\0\10\27\1\323"+
    "\6\27\1\324\10\27\24\0\10\27\6\0\6\27\4\0"+
    "\6\27\1\325\12\27\1\326\6\27\24\0\10\27\6\0"+
    "\6\27\4\0\17\27\1\235\10\27\24\0\10\27\6\0"+
    "\6\27\4\0\4\27\1\327\23\27\24\0\10\27\6\0"+
    "\6\27\4\0\21\27\1\330\6\27\24\0\10\331\6\0"+
    "\2\331\64\0\10\332\6\0\2\332\64\0\10\27\6\0"+
    "\6\27\4\0\17\27\1\333\10\27\24\0\2\27\1\334"+
    "\3\27\1\246\1\27\6\0\6\27\4\0\30\27\24\0"+
    "\5\27\1\335\2\27\6\0\6\27\4\0\30\27\24\0"+
    "\2\27\1\246\5\27\6\0\6\27\4\0\30\27\24\0"+
    "\4\27\1\246\3\27\6\0\6\27\4\0\30\27\24\0"+
    "\10\27\6\0\6\27\4\0\17\27\1\336\10\27\24\0"+
    "\10\27\6\0\6\27\4\0\10\27\1\337\17\27\24\0"+
    "\10\27\6\0\6\27\4\0\21\27\1\340\6\27\24\0"+
    "\10\27\6\0\6\27\4\0\5\27\1\341\22\27\24\0"+
    "\10\27\6\0\6\27\4\0\1\27\1\342\26\27\24\0"+
    "\10\27\6\0\6\27\4\0\1\343\27\27\24\0\10\27"+
    "\6\0\6\27\4\0\10\27\1\344\17\27\24\0\10\27"+
    "\6\0\6\27\4\0\17\27\1\345\10\27\24\0\10\27"+
    "\6\0\6\27\4\0\14\27\1\346\13\27\24\0\10\27"+
    "\6\0\6\27\4\0\3\27\1\347\24\27\24\0\10\27"+
    "\6\0\6\27\4\0\14\27\1\350\13\27\24\0\10\27"+
    "\6\0\6\27\4\0\2\27\1\351\25\27\24\0\10\27"+
    "\6\0\6\27\4\0\15\27\1\235\12\27\24\0\10\27"+
    "\6\0\6\27\4\0\20\27\1\352\7\27\24\0\10\27"+
    "\6\0\6\27\4\0\4\27\1\353\23\27\24\0\1\27"+
    "\1\265\1\266\1\267\1\246\1\27\1\270\1\246\6\0"+
    "\6\27\4\0\30\27\24\0\10\27\6\0\6\27\4\0"+
    "\4\27\1\354\23\27\24\0\10\27\6\0\6\27\4\0"+
    "\1\355\27\27\24\0\10\356\74\0\10\27\6\0\6\27"+
    "\4\0\20\27\1\357\7\27\24\0\10\27\6\0\6\27"+
    "\4\0\2\27\1\360\25\27\24\0\10\27\6\0\6\27"+
    "\4\0\15\27\1\361\12\27\24\0\10\27\6\0\6\27"+
    "\4\0\17\27\1\362\10\27\24\0\10\27\6\0\6\27"+
    "\4\0\14\27\1\363\13\27\24\0\10\27\6\0\6\27"+
    "\4\0\1\364\27\27\24\0\10\27\6\0\6\27\4\0"+
    "\1\365\27\27\24\0\10\27\6\0\6\27\4\0\4\27"+
    "\1\103\23\27\24\0\10\27\6\0\6\27\4\0\26\27"+
    "\1\235\1\27\24\0\10\27\6\0\6\27\4\0\10\27"+
    "\1\366\17\27\11\0\1\367\12\0\10\331\6\0\2\331"+
    "\54\0\1\367\7\0\10\332\6\0\2\332\64\0\10\27"+
    "\6\0\6\27\4\0\21\27\1\103\6\27\24\0\7\27"+
    "\1\246\6\0\6\27\4\0\30\27\24\0\6\27\1\246"+
    "\1\27\6\0\6\27\4\0\30\27\24\0\10\27\6\0"+
    "\6\27\4\0\14\27\1\370\13\27\24\0\10\27\6\0"+
    "\6\27\4\0\14\27\1\371\13\27\24\0\10\27\6\0"+
    "\6\27\4\0\4\27\1\176\23\27\24\0\10\27\6\0"+
    "\6\27\4\0\10\27\1\372\17\27\24\0\10\27\6\0"+
    "\6\27\4\0\12\27\1\373\15\27\24\0\10\27\6\0"+
    "\6\27\4\0\21\27\1\374\6\27\24\0\10\27\6\0"+
    "\6\27\4\0\2\27\1\375\25\27\24\0\10\27\6\0"+
    "\6\27\4\0\14\27\1\376\13\27\24\0\10\27\6\0"+
    "\6\27\4\0\3\27\1\176\24\27\24\0\10\27\6\0"+
    "\6\27\4\0\10\27\1\377\17\27\24\0\10\27\6\0"+
    "\6\27\4\0\6\27\1\246\21\27\24\0\10\27\6\0"+
    "\6\27\4\0\21\27\1\u0100\6\27\24\0\10\27\6\0"+
    "\6\27\4\0\5\27\1\u0101\22\27\24\0\10\27\6\0"+
    "\6\27\4\0\3\27\1\246\24\27\24\0\10\27\6\0"+
    "\6\27\4\0\20\27\1\246\7\27\24\0\10\27\6\0"+
    "\6\27\4\0\4\27\1\302\23\27\24\0\10\27\6\0"+
    "\6\27\4\0\3\27\1\360\24\27\24\0\10\27\6\0"+
    "\6\27\4\0\22\27\1\u0102\5\27\24\0\10\27\6\0"+
    "\6\27\4\0\22\27\1\u0103\5\27\24\0\10\27\6\0"+
    "\6\27\4\0\2\27\1\u0104\25\27\24\0\10\27\6\0"+
    "\6\27\4\0\21\27\1\u0105\6\27\24\0\10\27\6\0"+
    "\6\27\4\0\15\27\1\u0106\12\27\24\0\10\27\6\0"+
    "\6\27\4\0\1\u0107\27\27\24\0\10\27\6\0\6\27"+
    "\4\0\6\27\1\103\21\27\24\0\10\27\6\0\6\27"+
    "\4\0\4\27\1\150\23\27\24\0\10\27\6\0\6\27"+
    "\4\0\4\27\1\u0108\23\27\24\0\10\27\6\0\6\27"+
    "\4\0\4\27\1\u0109\23\27\24\0\10\27\6\0\6\27"+
    "\4\0\20\27\1\u010a\7\27\24\0\10\27\6\0\6\27"+
    "\4\0\21\27\1\u010b\6\27\24\0\10\27\6\0\6\27"+
    "\4\0\4\27\1\u010c\23\27\24\0\10\27\6\0\6\27"+
    "\4\0\2\27\1\u010d\25\27\24\0\10\27\6\0\6\27"+
    "\4\0\4\27\1\u010e\23\27\24\0\10\27\6\0\6\27"+
    "\4\0\21\27\1\u010f\6\27\24\0\10\27\6\0\6\27"+
    "\4\0\4\27\1\u0110\23\27\24\0\10\27\6\0\6\27"+
    "\4\0\14\27\1\u0111\13\27\24\0\10\27\6\0\6\27"+
    "\4\0\12\27\1\u0108\15\27\24\0\10\27\6\0\6\27"+
    "\4\0\26\27\1\u0112\1\27\24\0\10\27\6\0\6\27"+
    "\4\0\17\27\1\302\10\27\24\0\10\27\6\0\6\27"+
    "\4\0\21\27\1\u0113\6\27\24\0\10\27\6\0\6\27"+
    "\4\0\2\27\1\u0114\25\27\24\0\10\27\6\0\6\27"+
    "\4\0\15\27\1\150\12\27\24\0\10\27\6\0\6\27"+
    "\4\0\1\u0115\27\27\24\0\10\27\6\0\6\27\4\0"+
    "\12\27\1\u0116\15\27\24\0\10\27\6\0\6\27\4\0"+
    "\12\27\1\302\15\27\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[15844];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\2\1\1\11\2\1\2\11\2\1\1\11"+
    "\3\1\2\11\3\1\1\11\4\1\2\11\22\1\1\11"+
    "\1\1\3\11\1\0\1\11\3\0\1\1\1\0\2\1"+
    "\1\0\3\1\1\0\53\1\6\0\3\1\1\0\50\1"+
    "\2\0\2\1\1\0\16\1\2\0\31\1\1\0\13\1"+
    "\2\0\23\1\1\11\10\1\1\11\37\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[278];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }
    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  ScannerCup(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    return ZZ_CMAP[input];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Symbol(sym.ERROR, yychar, yyline, yytext());
            }
            // fall through
          case 48: break;
          case 2:
            { 
            }
            // fall through
          case 49: break;
          case 3:
            { return new Symbol(sym.Boolean_Op, yychar, yyline, yytext());
            }
            // fall through
          case 50: break;
          case 4:
            { return new Symbol(sym.Arithmetic_Op, yychar, yyline, yytext());
            }
            // fall through
          case 51: break;
          case 5:
            { return new Symbol(sym.Operator, yychar, yyline, yytext());
            }
            // fall through
          case 52: break;
          case 6:
            { return new Symbol(sym.O_Parentheses, yychar, yyline, yytext());
            }
            // fall through
          case 53: break;
          case 7:
            { return new Symbol(sym.C_Parentheses, yychar, yyline, yytext());
            }
            // fall through
          case 54: break;
          case 8:
            { return new Symbol(sym.Comma, yychar, yyline, yytext());
            }
            // fall through
          case 55: break;
          case 9:
            { return new Symbol(sym.Period, yychar, yyline, yytext());
            }
            // fall through
          case 56: break;
          case 10:
            { String str = yytext();
            while(str.substring(0, 1).equals("0")){
                str = str.substring(1);
            }
            return new Symbol(sym.Number, yychar, yyline, str);
            }
            // fall through
          case 57: break;
          case 11:
            { return new Symbol(sym.Colon, yychar, yyline, yytext());
            }
            // fall through
          case 58: break;
          case 12:
            { return new Symbol(sym.Semicolon, yychar, yyline, yytext());
            }
            // fall through
          case 59: break;
          case 13:
            { return new Symbol(sym.Equal, yychar, yyline, yytext());
            }
            // fall through
          case 60: break;
          case 14:
            { return new Symbol(sym.QuestionMark, yychar, yyline, yytext());
            }
            // fall through
          case 61: break;
          case 15:
            { return new Symbol(sym.Identifier, yychar, yyline, yytext());
            }
            // fall through
          case 62: break;
          case 16:
            { return new Symbol(sym.O_Brackets, yychar, yyline, yytext());
            }
            // fall through
          case 63: break;
          case 17:
            { return new Symbol(sym.C_Brackets, yychar, yyline, yytext());
            }
            // fall through
          case 64: break;
          case 18:
            { return new Symbol(sym.Caret, yychar, yyline, yytext());
            }
            // fall through
          case 65: break;
          case 19:
            { return new Symbol(sym.O_Braces, yychar, yyline, yytext());
            }
            // fall through
          case 66: break;
          case 20:
            { return new Symbol(sym.C_Braces, yychar, yyline, yytext());
            }
            // fall through
          case 67: break;
          case 21:
            { return new Symbol(sym.String, yychar, yyline, yytext());
            }
            // fall through
          case 68: break;
          case 22:
            { return new Symbol(sym.Reserved, yychar, yyline, yytext());
            }
            // fall through
          case 69: break;
          case 23:
            { return new Symbol(sym.Do, yychar, yyline, yytext());
            }
            // fall through
          case 70: break;
          case 24:
            { return new Symbol(sym.If, yychar, yyline, yytext());
            }
            // fall through
          case 71: break;
          case 25:
            { return new Symbol(sym.For, yychar, yyline, yytext());
            }
            // fall through
          case 72: break;
          case 26:
            { return new Symbol(sym.Var_Type, yychar, yyline, yytext());
            }
            // fall through
          case 73: break;
          case 27:
            { return new Symbol(sym.Units, yychar, yyline, yytext());
            }
            // fall through
          case 74: break;
          case 28:
            { return new Symbol(sym.Boolean_Value, yychar, yyline, yytext());
            }
            // fall through
          case 75: break;
          case 29:
            { return new Symbol(sym.Transac, yychar, yyline, yytext());
            }
            // fall through
          case 76: break;
          case 30:
            { return new Symbol(sym.Else, yychar, yyline, yytext());
            }
            // fall through
          case 77: break;
          case 31:
            { return new Symbol(sym.Enum, yychar, yyline, yytext());
            }
            // fall through
          case 78: break;
          case 32:
            { return new Symbol(sym.This, yychar, yyline, yytext());
            }
            // fall through
          case 79: break;
          case 33:
            { return new Symbol(sym.Break, yychar, yyline, yytext());
            }
            // fall through
          case 80: break;
          case 34:
            { return new Symbol(sym.While, yychar, yyline, yytext());
            }
            // fall through
          case 81: break;
          case 35:
            { return new Symbol(sym.Pragma, yychar, yyline, yytext());
            }
            // fall through
          case 82: break;
          case 36:
            { return new Symbol(sym.Version, yychar, yyline, yytext());
            }
            // fall through
          case 83: break;
          case 37:
            { return new Symbol(sym.Hexadecimal, yychar, yyline, yytext());
            }
            // fall through
          case 84: break;
          case 38:
            { return new Symbol(sym.Public, yychar, yyline, yytext());
            }
            // fall through
          case 85: break;
          case 39:
            { return new Symbol(sym.Return, yychar, yyline, yytext());
            }
            // fall through
          case 86: break;
          case 40:
            { return new Symbol(sym.Struct, yychar, yyline, yytext());
            }
            // fall through
          case 87: break;
          case 41:
            { return new Symbol(sym.Modifier, yychar, yyline, yytext());
            }
            // fall through
          case 88: break;
          case 42:
            { return new Symbol(sym.Private, yychar, yyline, yytext());
            }
            // fall through
          case 89: break;
          case 43:
            { return new Symbol(sym.Returns, yychar, yyline, yytext());
            }
            // fall through
          case 90: break;
          case 44:
            { return new Symbol(sym.Continue, yychar, yyline, yytext());
            }
            // fall through
          case 91: break;
          case 45:
            { return new Symbol(sym.Contract, yychar, yyline, yytext());
            }
            // fall through
          case 92: break;
          case 46:
            { return new Symbol(sym.Function, yychar, yyline, yytext());
            }
            // fall through
          case 93: break;
          case 47:
            { return new Symbol(sym.Solidity, yychar, yyline, yytext());
            }
            // fall through
          case 94: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
