// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: progra.jflex

import java.util.*;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class dios {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\13\0\3\1\23\0\1\2\3\0\1\3\1\4\1\0"+
    "\2\3\1\5\1\2\1\3\1\2\1\3\1\2\2\6"+
    "\1\7\7\6\2\3\1\10\1\11\1\12\1\3\1\0"+
    "\16\13\1\14\1\15\6\13\1\16\3\13\1\3\1\0"+
    "\2\3\2\0\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\13\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\13\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\3\1\47\2\3\6\0"+
    "\1\1\u01a2\0\2\1\326\0\u0100\1";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\6\3\23\4\1\3\2\4\1\5"+
    "\70\4\1\5\22\4\1\6\5\4\1\5\1\7\20\4"+
    "\1\7\6\4\1\5\37\4\1\5\17\4";

  private static int [] zzUnpackAction() {
    int [] result = new int[186];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\50\0\120\0\50\0\170\0\240\0\310"+
    "\0\360\0\u0118\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0\0\u0208"+
    "\0\u0230\0\u0258\0\u0280\0\u02a8\0\u02d0\0\u02f8\0\u0320\0\u0348"+
    "\0\u0370\0\u0398\0\u03c0\0\u03e8\0\u0410\0\u0438\0\u0460\0\u0118"+
    "\0\u0488\0\u04b0\0\u04d8\0\u0500\0\u0528\0\u0550\0\u0578\0\u05a0"+
    "\0\u05c8\0\u05f0\0\u0618\0\u0640\0\u0668\0\u0690\0\u06b8\0\u06e0"+
    "\0\u0708\0\u0730\0\u0758\0\u0780\0\u07a8\0\u07d0\0\u07f8\0\u0820"+
    "\0\u0848\0\u0870\0\u0898\0\u08c0\0\u08e8\0\u0910\0\u0938\0\u0960"+
    "\0\u0988\0\u09b0\0\u09d8\0\u0a00\0\u0a28\0\u0a50\0\u0a78\0\u0aa0"+
    "\0\u0ac8\0\u0af0\0\u0b18\0\u0b40\0\u0b68\0\u0b90\0\u0bb8\0\u0be0"+
    "\0\u0c08\0\u0c30\0\u0c58\0\u0c80\0\u0ca8\0\u0cd0\0\u0cf8\0\u0d20"+
    "\0\u0d48\0\u0d70\0\u0d98\0\u0dc0\0\u0de8\0\u0e10\0\u0e38\0\u0e60"+
    "\0\u0e88\0\u0eb0\0\u0ed8\0\u0f00\0\u0f28\0\u0f50\0\u0f78\0\u0fa0"+
    "\0\u0fc8\0\u0ff0\0\u1018\0\u0118\0\u1040\0\u1068\0\u1090\0\u10b8"+
    "\0\u10e0\0\u1108\0\u1130\0\u1158\0\u1180\0\u11a8\0\u11d0\0\u11f8"+
    "\0\u1220\0\u1248\0\u1270\0\u1298\0\u12c0\0\u12e8\0\u1310\0\u1338"+
    "\0\u1360\0\u1388\0\u13b0\0\u0118\0\u13d8\0\u1400\0\u1428\0\u1450"+
    "\0\u1478\0\u14a0\0\u14c8\0\u14f0\0\u1518\0\u1540\0\u1568\0\u1590"+
    "\0\u15b8\0\u15e0\0\u1608\0\u1630\0\u1658\0\u1680\0\u16a8\0\u16d0"+
    "\0\u16f8\0\u1720\0\u1748\0\u1770\0\u1798\0\u17c0\0\u17e8\0\u1810"+
    "\0\u1838\0\u1860\0\u1888\0\u18b0\0\u18d8\0\u1900\0\u1928\0\u1950"+
    "\0\u1978\0\u19a0\0\u0f50\0\u19c8\0\u19f0\0\u1a18\0\u1a40\0\u1a68"+
    "\0\u1a90\0\u1ab8\0\u1ae0\0\u1b08\0\u1b30\0\u1b58\0\u1b80\0\u1ba8"+
    "\0\u1bd0\0\u1bf8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[186];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\2\2\1\10"+
    "\1\4\1\11\2\12\1\13\1\12\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\12\1\22\1\23\2\12\1\24"+
    "\2\12\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\12\1\34\1\12\1\35\61\0\1\5\42\0\1\5"+
    "\50\0\1\5\3\0\1\5\46\0\2\5\47\0\2\5"+
    "\43\0\2\12\3\0\34\12\7\0\2\12\3\0\23\12"+
    "\1\36\10\12\7\0\2\12\3\0\7\12\1\37\14\12"+
    "\1\40\7\12\7\0\2\12\3\0\4\12\1\41\14\12"+
    "\1\42\1\12\1\43\6\12\1\44\1\12\7\0\2\12"+
    "\3\0\4\12\1\45\14\12\1\46\12\12\7\0\2\12"+
    "\3\0\4\12\1\47\3\12\1\50\10\12\1\40\12\12"+
    "\7\0\2\12\3\0\16\12\1\51\1\12\1\52\4\12"+
    "\1\53\6\12\7\0\2\12\3\0\4\12\1\54\7\12"+
    "\1\55\4\12\1\56\1\12\1\57\2\12\1\60\5\12"+
    "\7\0\2\12\3\0\10\12\1\61\10\12\1\62\12\12"+
    "\7\0\2\12\3\0\11\12\1\40\5\12\1\63\1\64"+
    "\13\12\7\0\2\12\3\0\4\12\1\65\7\12\1\66"+
    "\4\12\1\67\12\12\7\0\2\12\3\0\4\12\1\70"+
    "\16\12\1\71\2\12\1\72\5\12\7\0\2\12\3\0"+
    "\10\12\1\73\23\12\7\0\2\12\3\0\10\12\1\74"+
    "\10\12\1\75\3\12\1\76\5\12\1\77\7\0\2\12"+
    "\3\0\13\12\1\100\7\12\1\101\10\12\7\0\2\12"+
    "\3\0\11\12\1\102\2\12\1\103\17\12\7\0\2\12"+
    "\3\0\4\12\1\56\7\12\1\104\17\12\7\0\2\12"+
    "\3\0\10\12\1\105\2\12\1\106\20\12\7\0\2\12"+
    "\3\0\10\12\1\107\23\12\50\0\1\5\6\0\2\12"+
    "\3\0\4\12\1\110\27\12\7\0\2\12\3\0\7\12"+
    "\1\111\24\12\7\0\2\12\3\0\16\12\1\112\15\12"+
    "\7\0\2\12\3\0\21\12\1\113\12\12\7\0\2\12"+
    "\3\0\10\12\1\114\23\12\7\0\2\12\3\0\25\12"+
    "\1\115\6\12\7\0\2\12\3\0\16\12\1\116\15\12"+
    "\7\0\2\12\3\0\20\12\1\117\13\12\7\0\2\12"+
    "\3\0\32\12\1\120\1\12\7\0\2\12\3\0\16\12"+
    "\1\121\15\12\7\0\2\12\3\0\24\12\1\122\7\12"+
    "\7\0\2\12\3\0\26\12\1\123\5\12\7\0\2\12"+
    "\3\0\13\12\1\124\20\12\7\0\2\12\3\0\16\12"+
    "\1\51\15\12\7\0\2\12\3\0\20\12\1\125\13\12"+
    "\7\0\2\12\3\0\23\12\1\40\10\12\7\0\2\12"+
    "\3\0\21\12\1\123\12\12\7\0\2\12\3\0\20\12"+
    "\1\126\13\12\7\0\2\12\3\0\31\12\1\40\2\12"+
    "\7\0\2\12\3\0\26\12\1\127\5\12\7\0\2\12"+
    "\3\0\22\12\1\130\11\12\7\0\2\12\3\0\25\12"+
    "\1\131\6\12\7\0\2\12\3\0\22\12\1\132\11\12"+
    "\7\0\2\12\3\0\20\12\1\133\13\12\7\0\2\12"+
    "\3\0\7\12\1\134\24\12\7\0\2\12\3\0\32\12"+
    "\1\135\1\12\7\0\2\12\3\0\14\12\1\136\17\12"+
    "\7\0\2\12\3\0\5\12\1\137\26\12\7\0\2\12"+
    "\3\0\25\12\1\140\6\12\7\0\2\12\3\0\6\12"+
    "\1\141\11\12\1\142\13\12\7\0\2\12\3\0\16\12"+
    "\1\143\15\12\7\0\2\12\3\0\23\12\1\144\10\12"+
    "\7\0\2\12\3\0\4\12\1\145\27\12\7\0\2\12"+
    "\3\0\14\12\1\146\17\12\7\0\2\12\3\0\4\12"+
    "\1\147\21\12\1\122\5\12\7\0\2\12\3\0\14\12"+
    "\1\150\17\12\7\0\2\12\3\0\20\12\1\151\13\12"+
    "\7\0\2\12\3\0\10\12\1\152\23\12\7\0\2\12"+
    "\3\0\10\12\1\153\3\12\1\154\17\12\7\0\2\12"+
    "\3\0\14\12\1\155\17\12\7\0\2\12\3\0\4\12"+
    "\1\127\27\12\7\0\2\12\3\0\12\12\1\156\21\12"+
    "\7\0\2\12\3\0\23\12\1\157\10\12\7\0\2\12"+
    "\3\0\4\12\1\160\27\12\7\0\2\12\3\0\16\12"+
    "\1\40\15\12\7\0\2\12\3\0\4\12\1\161\27\12"+
    "\7\0\2\12\3\0\10\12\1\162\23\12\7\0\2\12"+
    "\3\0\16\12\1\163\15\12\7\0\2\12\3\0\24\12"+
    "\1\164\1\165\6\12\7\0\2\12\3\0\24\12\1\154"+
    "\7\12\7\0\2\12\3\0\10\12\1\166\23\12\7\0"+
    "\2\12\3\0\10\12\1\40\23\12\7\0\2\12\3\0"+
    "\17\12\1\40\14\12\7\0\2\12\3\0\10\12\1\167"+
    "\23\12\7\0\2\12\3\0\20\12\1\170\13\12\7\0"+
    "\2\12\3\0\6\12\1\171\25\12\7\0\2\12\3\0"+
    "\23\12\1\120\10\12\7\0\2\12\3\0\21\12\1\172"+
    "\12\12\7\0\2\12\3\0\10\12\1\173\23\12\7\0"+
    "\2\12\3\0\22\12\1\174\11\12\7\0\2\12\3\0"+
    "\26\12\1\175\5\12\7\0\2\12\3\0\14\12\1\176"+
    "\17\12\7\0\2\12\3\0\4\12\1\177\27\12\7\0"+
    "\2\12\3\0\27\12\1\200\4\12\7\0\2\12\3\0"+
    "\16\12\1\201\15\12\7\0\2\12\3\0\26\12\1\202"+
    "\5\12\7\0\2\12\3\0\21\12\1\203\12\12\7\0"+
    "\2\12\3\0\7\12\1\204\24\12\7\0\2\12\3\0"+
    "\14\12\1\205\17\12\7\0\2\12\3\0\14\12\1\206"+
    "\11\12\1\207\5\12\7\0\2\12\3\0\5\12\1\210"+
    "\26\12\7\0\2\12\3\0\24\12\1\40\7\12\7\0"+
    "\2\12\3\0\20\12\1\211\13\12\7\0\2\12\3\0"+
    "\31\12\1\212\2\12\7\0\2\12\3\0\25\12\1\213"+
    "\6\12\7\0\2\12\3\0\30\12\1\40\3\12\7\0"+
    "\2\12\3\0\15\12\1\120\16\12\7\0\2\12\3\0"+
    "\16\12\1\122\15\12\7\0\2\12\3\0\17\12\1\214"+
    "\14\12\7\0\2\12\3\0\10\12\1\215\23\12\7\0"+
    "\2\12\3\0\20\12\1\216\13\12\7\0\2\12\3\0"+
    "\15\12\1\40\16\12\7\0\2\12\3\0\24\12\1\213"+
    "\7\12\7\0\2\12\3\0\6\12\1\217\25\12\7\0"+
    "\2\12\3\0\25\12\1\220\6\12\7\0\2\12\3\0"+
    "\14\12\1\221\6\12\1\222\10\12\7\0\2\12\3\0"+
    "\12\12\1\223\12\12\1\122\6\12\7\0\2\12\3\0"+
    "\23\12\1\154\10\12\7\0\2\12\3\0\10\12\1\224"+
    "\23\12\7\0\2\12\3\0\25\12\1\225\6\12\7\0"+
    "\2\12\3\0\23\12\1\226\10\12\7\0\2\12\3\0"+
    "\23\12\1\227\10\12\7\0\2\12\3\0\14\12\1\206"+
    "\17\12\7\0\2\12\3\0\25\12\1\230\6\12\7\0"+
    "\2\12\3\0\11\12\1\231\22\12\7\0\2\12\3\0"+
    "\5\12\1\155\26\12\7\0\2\12\3\0\4\12\1\232"+
    "\27\12\7\0\2\12\3\0\14\12\1\233\17\12\7\0"+
    "\2\12\3\0\23\12\1\234\10\12\7\0\2\12\3\0"+
    "\20\12\1\235\13\12\7\0\2\12\3\0\7\12\1\236"+
    "\24\12\7\0\2\12\3\0\20\12\1\237\13\12\7\0"+
    "\2\12\3\0\6\12\1\226\25\12\7\0\2\12\3\0"+
    "\21\12\1\154\12\12\7\0\2\12\3\0\24\12\1\240"+
    "\7\12\7\0\2\12\3\0\10\12\1\241\23\12\7\0"+
    "\2\12\3\0\2\12\1\242\31\12\7\0\2\12\3\0"+
    "\4\12\1\40\27\12\7\0\2\12\3\0\24\12\1\146"+
    "\7\12\7\0\2\12\3\0\6\12\1\243\25\12\7\0"+
    "\2\12\3\0\21\12\1\244\12\12\7\0\2\12\3\0"+
    "\23\12\1\245\10\12\7\0\2\12\3\0\20\12\1\246"+
    "\13\12\7\0\2\12\3\0\4\12\1\207\27\12\7\0"+
    "\2\12\3\0\4\12\1\247\27\12\7\0\2\12\3\0"+
    "\32\12\1\154\1\12\7\0\2\12\3\0\14\12\1\250"+
    "\17\12\7\0\2\12\3\0\25\12\1\40\6\12\7\0"+
    "\2\12\3\0\20\12\1\251\13\12\7\0\2\12\3\0"+
    "\10\12\1\120\23\12\7\0\2\12\3\0\14\12\1\252"+
    "\17\12\7\0\2\12\3\0\25\12\1\122\6\12\7\0"+
    "\2\12\3\0\6\12\1\40\25\12\7\0\2\12\3\0"+
    "\20\12\1\253\13\12\7\0\2\12\3\0\7\12\1\120"+
    "\24\12\7\0\2\12\3\0\14\12\1\254\17\12\7\0"+
    "\2\12\3\0\12\12\1\40\21\12\7\0\2\12\3\0"+
    "\11\12\1\255\22\12\7\0\2\12\3\0\7\12\1\40"+
    "\24\12\7\0\2\12\3\0\1\12\1\256\32\12\7\0"+
    "\2\12\3\0\10\12\1\204\23\12\7\0\2\12\3\0"+
    "\7\12\1\243\24\12\7\0\2\12\3\0\26\12\1\257"+
    "\5\12\7\0\2\12\3\0\26\12\1\122\5\12\7\0"+
    "\2\12\3\0\25\12\1\260\6\12\7\0\2\12\3\0"+
    "\21\12\1\261\12\12\7\0\2\12\3\0\4\12\1\113"+
    "\27\12\7\0\2\12\3\0\10\12\1\56\23\12\7\0"+
    "\2\12\3\0\25\12\1\262\6\12\7\0\2\12\3\0"+
    "\10\12\1\263\23\12\7\0\2\12\3\0\3\12\1\264"+
    "\30\12\7\0\2\12\3\0\6\12\1\265\25\12\7\0"+
    "\2\12\3\0\10\12\1\266\23\12\7\0\2\12\3\0"+
    "\20\12\1\40\13\12\7\0\2\12\3\0\32\12\1\40"+
    "\1\12\7\0\2\12\3\0\23\12\1\204\10\12\7\0"+
    "\1\12\1\40\3\0\34\12\7\0\2\12\3\0\25\12"+
    "\1\267\6\12\7\0\2\12\3\0\6\12\1\270\25\12"+
    "\7\0\2\12\3\0\21\12\1\56\12\12\7\0\2\12"+
    "\3\0\4\12\1\271\27\12\7\0\2\12\3\0\16\12"+
    "\1\272\15\12\7\0\2\12\3\0\16\12\1\204\15\12"+
    "\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7200];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\1\11\265\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[186];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    List<String> indentifiers = new ArrayList();
    List<String> operators = new ArrayList();
    List<String> reserved = new ArrayList();
    List<String> transac = new ArrayList();
    List<String> units = new ArrayList();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  dios(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    System.out.print("Identificadores: ");
    for(int i=0; i<indentifiers.size();i++){
        if(i==indentifiers.size()-1)
            System.out.print(indentifiers.get(i)+"\n");
        else
            System.out.print(indentifiers.get(i)+", ");
    }
    System.out.print("Operadores: ");
    for(int i=0; i<operators.size();i++){
        if(i==operators.size()-1)
            System.out.print(operators.get(i)+"\n");
        else
            System.out.print(operators.get(i)+", ");
    }
    System.out.print("Palabras reservadas: ");
    for(int i=0; i<reserved.size();i++){
        if(i==reserved.size()-1)
            System.out.print(reserved.get(i)+"\n");
        else
            System.out.print(reserved.get(i)+", ");
    }
    System.out.print("Palabras TRANSAC: ");
    for(int i=0; i<transac.size();i++){
        if(i==transac.size()-1)
            System.out.print(transac.get(i)+"\n");
        else
            System.out.print(transac.get(i)+", ");
    }
    System.out.print("Palabras UNITS: ");
    for(int i=0; i<units.size();i++){
        if(i==units.size()-1)
            System.out.print(units.get(i)+"\n");
        else
            System.out.print(units.get(i)+", ");
    }
    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { 
            }
            // fall through
          case 8: break;
          case 2:
            { System.out.print(yytext());
            }
            // fall through
          case 9: break;
          case 3:
            { operators.add(yytext());
            }
            // fall through
          case 10: break;
          case 4:
            { indentifiers.add(yytext());
            }
            // fall through
          case 11: break;
          case 5:
            { reserved.add(yytext());
            }
            // fall through
          case 12: break;
          case 6:
            { units.add(yytext());
            }
            // fall through
          case 13: break;
          case 7:
            { transac.add(yytext());
            }
            // fall through
          case 14: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java dios [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        dios scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new dios(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
